-- Supabase-ready PostgreSQL schema for ExamNexus
-- This is adapted from your MySQL schema so it can be imported into Supabase SQL Editor.

CREATE TABLE IF NOT EXISTS users (
    id text PRIMARY KEY,
    name text NOT NULL,
    email text UNIQUE NOT NULL,
    dept text NOT NULL,
    password text NOT NULL,
    role text NOT NULL CHECK (role IN ('student', 'teacher')),
    is_provisional boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_provisional boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS portal_users (
    id text PRIMARY KEY,
    name text NOT NULL,
    email text UNIQUE NOT NULL,
    password text NOT NULL,
    role text NOT NULL CHECK (role IN ('student', 'teacher')),
    dept text NOT NULL DEFAULT 'CSE',
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS exam_students (
    id text PRIMARY KEY,
    name text NOT NULL,
    email text UNIQUE NOT NULL,
    dept text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS halls (
    room_number text PRIMARY KEY,
    capacity integer NOT NULL CHECK (capacity > 0)
);

CREATE TABLE IF NOT EXISTS student_seating (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id text NOT NULL REFERENCES exam_students(id) ON UPDATE CASCADE ON DELETE CASCADE,
    course_code text NOT NULL,
    exam_date date NOT NULL,
    exam_time text NOT NULL,
    room_number text NOT NULL REFERENCES halls(room_number) ON UPDATE CASCADE ON DELETE CASCADE,
    seat_vector text NOT NULL,
    status text NOT NULL DEFAULT 'Assigned' CHECK (status IN ('Assigned', 'Pending'))
);

CREATE TABLE IF NOT EXISTS student_seating_traditional (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id text NOT NULL REFERENCES exam_students(id) ON UPDATE CASCADE ON DELETE CASCADE,
    course_code text NOT NULL,
    exam_date date NOT NULL,
    exam_time text NOT NULL,
    room_number text NOT NULL REFERENCES halls(room_number) ON UPDATE CASCADE ON DELETE CASCADE,
    seat_vector text NOT NULL,
    status text NOT NULL DEFAULT 'Assigned' CHECK (status IN ('Assigned', 'Pending'))
);

CREATE TABLE IF NOT EXISTS duties (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    room_number text NOT NULL REFERENCES halls(room_number) ON DELETE CASCADE,
    status text NOT NULL DEFAULT 'Assigned' CHECK (status IN ('Assigned', 'Completed')),
    duty_date date,
    UNIQUE (teacher_id, room_number, duty_date)
);

-- Enable access for the browser app using the anon key
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE portal_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE halls ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_students ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_seating ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_seating_traditional ENABLE ROW LEVEL SECURITY;
ALTER TABLE duties ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "allow_public_select_users" ON users;
CREATE POLICY "allow_public_select_users" ON users
    FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "allow_public_insert_users" ON users;
CREATE POLICY "allow_public_insert_users" ON users
    FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "allow_public_update_users" ON users;
CREATE POLICY "allow_public_update_users" ON users
    FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_public_delete_users" ON users;
CREATE POLICY "allow_public_delete_users" ON users
    FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "allow_public_select_portal_users" ON portal_users;
CREATE POLICY "allow_public_select_portal_users" ON portal_users
    FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "allow_public_insert_portal_users" ON portal_users;
CREATE POLICY "allow_public_insert_portal_users" ON portal_users
    FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "allow_public_update_portal_users" ON portal_users;
CREATE POLICY "allow_public_update_portal_users" ON portal_users
    FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_public_delete_portal_users" ON portal_users;
CREATE POLICY "allow_public_delete_portal_users" ON portal_users
    FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "allow_public_select_exam_students" ON exam_students;
CREATE POLICY "allow_public_select_exam_students" ON exam_students
    FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "allow_public_insert_exam_students" ON exam_students;
CREATE POLICY "allow_public_insert_exam_students" ON exam_students
    FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "allow_public_update_exam_students" ON exam_students;
CREATE POLICY "allow_public_update_exam_students" ON exam_students
    FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_public_delete_exam_students" ON exam_students;
CREATE POLICY "allow_public_delete_exam_students" ON exam_students
    FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "allow_public_insert_portal_users" ON portal_users;
CREATE POLICY "allow_public_insert_portal_users" ON portal_users
    FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "allow_public_update_portal_users" ON portal_users;
CREATE POLICY "allow_public_update_portal_users" ON portal_users
    FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_public_delete_portal_users" ON portal_users;
CREATE POLICY "allow_public_delete_portal_users" ON portal_users
    FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "allow_public_select_halls" ON halls;
CREATE POLICY "allow_public_select_halls" ON halls
    FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "allow_public_insert_halls" ON halls;
CREATE POLICY "allow_public_insert_halls" ON halls
    FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "allow_public_update_halls" ON halls;
CREATE POLICY "allow_public_update_halls" ON halls
    FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_public_delete_halls" ON halls;
CREATE POLICY "allow_public_delete_halls" ON halls
    FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "allow_public_select_student_seating" ON student_seating;
CREATE POLICY "allow_public_select_student_seating" ON student_seating
    FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "allow_public_insert_student_seating" ON student_seating;
CREATE POLICY "allow_public_insert_student_seating" ON student_seating
    FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "allow_public_update_student_seating" ON student_seating;
CREATE POLICY "allow_public_update_student_seating" ON student_seating
    FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_public_delete_student_seating" ON student_seating;
CREATE POLICY "allow_public_delete_student_seating" ON student_seating
    FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "allow_public_select_student_seating_traditional" ON student_seating_traditional;
CREATE POLICY "allow_public_select_student_seating_traditional" ON student_seating_traditional
    FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "allow_public_insert_student_seating_traditional" ON student_seating_traditional;
CREATE POLICY "allow_public_insert_student_seating_traditional" ON student_seating_traditional
    FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "allow_public_update_student_seating_traditional" ON student_seating_traditional;
CREATE POLICY "allow_public_update_student_seating_traditional" ON student_seating_traditional
    FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_public_delete_student_seating_traditional" ON student_seating_traditional;
CREATE POLICY "allow_public_delete_student_seating_traditional" ON student_seating_traditional
    FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "allow_public_select_duties" ON duties;
CREATE POLICY "allow_public_select_duties" ON duties
    FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "allow_public_insert_duties" ON duties;
CREATE POLICY "allow_public_insert_duties" ON duties
    FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "allow_public_update_duties" ON duties;
CREATE POLICY "allow_public_update_duties" ON duties
    FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_public_delete_duties" ON duties;
CREATE POLICY "allow_public_delete_duties" ON duties
    FOR DELETE TO anon, authenticated USING (true);

-- Seed data
INSERT INTO halls (room_number, capacity)
VALUES ('502', 40), ('403', 35)
ON CONFLICT (room_number) DO NOTHING;

INSERT INTO users (id, name, email, dept, password, role, is_provisional)
VALUES
    ('211-115-001', 'Tahmid Ahmed', '211-115-001@metrouni.edu.bd', 'CSE', 'student123', 'student', false),
    ('hasan.m@metrouni.edu.bd', 'Dr. M. Hasan', 'hasan.m@metrouni.edu.bd', 'CSE', 'teacher123', 'teacher', false),
    ('211-115-100', 'Aloy', '211-115-100@metrouni.edu.bd', 'CSE', 'student456', 'student', false)
ON CONFLICT (id) DO NOTHING;

INSERT INTO student_seating (student_id, course_code, exam_date, exam_time, room_number, seat_vector, status)
VALUES ('211-115-001', 'CSE-411', '2026-07-15', '10:00 AM - 1:00 PM', '502', 'Row-B / Desk-14', 'Assigned');
